### ISSUE TITLE
I had fallen and I can't get up

### ISSUE THREAD

**Issue by nguyenel** [EasonDEFGH/-#1]
Game Crashed! I have fallen and I can't get up! If this has happened more than once then please copy the text on this screen and publish it in the issues feed of this fork's GitHub repository.

The URL to this fork's GitHub repository is: https://github.com/lax1dude/eaglercraft

java.lang.IndexOutOfBoundsException

Error: Java exception thrown
    at $rt_exception (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:10:390)
    at $rt_throw (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:10:218)
    at ALk (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:3366:62)
    at Z (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:3358:17)
    at BaP (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:8768:456)
    at B$q (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:8762:154)
    at $rt_array.toString [as gv] (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:18839:372)
    at B_q (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:4417:274)
    at BpZ (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:4414:243)
    at BG1 (https://superteamxx.github.io/Minecraft-Unblocked/javascript/classes.js:3481:85)

eaglercraft.version = "22w42b"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "lax1dude"
eaglercraft.username = "Jacks"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)
webgl.vendor = Intel Open Source Technology Center

webgl.anisotropicGlitch = false

window.eaglercraftOpts = {"servers":[{"serverAddress":"localhost:25565","hideAddress":false,"serverName":"Local Test Server"}],"container":"game_frame","relays":[{"addr":"wss://relay.deev.is/","primary":true,"name":"lax1dude relay #1"},{"addr":"wss://relay.lax1dude.net/","primary":false,"name":"lax1dude relay #2"},{"addr":"wss://relay.shhnowisnottheti.me/","primary":false,"name":"ayunami relay #1"}],"assetOverrides":{"records/13.mp3":"https://s2.radio.co/s2b2b68744/listen","records/wait.mp3":"wait.mp3","records/blocks.mp3":"https://www.ophanim.net:8444/s/9780","records/strad.mp3":"http://listen.011fm.com:8028/stream15","records/ward.mp3":"http://fr4.1mix.co.uk:8000/192h","records/cat.mp3":"http://usa9.fastcast4u.com/proxy/jamz?mp=/1","records/far.mp3":"https://stream.nightride.fm/nightride.m4a","records/mellohi.mp3":"https://stream.nightride.fm/chillsynth.m4a"},"mainMenu":{"splashes":["Darviglet!","eaglerenophile!","You Eagler!","Yeeeeeee!","yeee","EEEEEEEEE!","You Darvig!","You Vigg!",":>","|>","You Yumpster!"],"eaglerLogo":false},"assetsURI":"assets.epk","serverWorkerURI":"worker_bootstrap.js","worldsFolder":"TEST"}

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1366
rootElement.clientHeight = 768
window.innerWidth = 1366
window.innerHeight = 768
window.outerWidth = 1366
window.outerHeight = 768
window.devicePixelRatio = 1
window.screen.availWidth = 1366
window.screen.availHeight = 768
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = https://superteamxx.github.io/Minecraft-Unblocked/javascript/

----- Begin Minecraft Config -----
CgAACQAGcmVsYXlzCgAAAAMIAARhZGRyABR3c3M6Ly9yZWxheS5kZWV2LmlzLwEAB3ByaW1hcnkBCAAHY29tbWVudAARbGF4MWR1ZGUgcmVsYXkgIzEACAAEYWRkcgAZd3NzOi8vcmVsYXkubGF4MWR1ZGUubmV0LwEAB3ByaW1hcnkACAAHY29tbWVudAARbGF4MWR1ZGUgcmVsYXkgIzIACAAEYWRkcgAgd3NzOi8vcmVsYXkuc2hobm93aXNub3R0aGV0aS5tZS8BAAdwcmltYXJ5AAgAB2NvbW1lbnQAEGF5dW5hbWkgcmVsYXkgIzEAAwAIa2V5Lnpvb20AAAAuAwAMa2V5LnBpY2tJdGVt////ngEAD2NoYXRMaW5rc1Byb21wdAEDAAxrZXkuZnVuY3Rpb24AAAAhAwAIa2V5LmNoYXQAAAAUAQAOc2hvd1NraW5KYWNrZXQBAwAKa2V5LnNwcmludAAAABMFAAtzb3VuZFZvbHVtZT+AAAADAA5jaGF0VmlzaWJpbGl0eQAAAAADABF2b2ljZUxpc3RlblJhZGl1cwAAABABABBzaG93U2tpblJpZ2h0TGVnAQMADWtleS5pbnZlbnRvcnkAAAASAQAPc2hvd1NraW5MZWZ0TGVnAQEADmFsbG93Rk5BV1NraW5zAQEAEWhpZGVTZXJ2ZXJBZGRyZXNzAAEAC3ZpZXdCb2JiaW5nAQEADHJlbGF5VGltZW91dAQJAAdzZXJ2ZXJzAQAAAAABABBhZHZhbmNlZFRvb2x0aXBzAAUAEXZvaWNlTGlzdGVuVm9sdW1lPwAAAAUAC2NoYXRPcGFjaXR5P4AAAAMACGtleS5iYWNrAAAAHwEADGhpZGVKb2luQ29kZQADAApmb3JjZVdpZHRoAAAAAAMADGNodW5rVXBkYXRlcwAAAAADAAhrZXkuZHJvcAAAABAFAAttdXNpY1ZvbHVtZT+AAAAFAAtzZW5zaXRpdml0eT8AAAABABBwYXVzZU9uTG9zdEZvY3VzAQMAC3ZvaWNlUFRUS2V5AAAALwEAC3Nob3dTa2luSGF0AQUABWdhbW1hP4AAAAMACXBhcnRpY2xlcwAAAAIBAA5zaG93T3RoZXJDYXBlcwEBAAtjaGF0Q29sb3VycwEDAAhrZXkubGVmdAAAAB4DAAtrZXkuZm9yd2FyZAAAABEDAAprZXkuYXR0YWNr////nAMADHZpZXdEaXN0YW5jZQAAAAABAApkaWZmaWN1bHR5AAEAA2ZvZwABAA9zaG93Q29vcmRpbmF0ZXMBAQAJY2hhdExpbmtzAQMACWtleS5zbmVhawAAACoDAAlrZXkucmlnaHQAAAAgBQADZm92AAAAAAUACWNoYXRXaWR0aD+AAAADAAhndWlTY2FsZQAAAAMDAA5saW1pdEZyYW1lcmF0ZQAAAAAFAAljaGF0U2NhbGU/gAAAAQAIYWRkZXJhbGwAAQAUc2VlbkFja25vd2xlZGdlbWVudHMBAwAQYW1iaWVudE9jY2x1c2lvbgAAAAIFABFjaGF0SGVpZ2h0Rm9jdXNlZD+AAAABABBoZWxkSXRlbVRvb2x0aXBzAQEACGFuYWdseXBoAAgACGxhbmd1YWdlAAVlbl9VUwEAEHNob3dTa2luUmlnaHRBcm0BAQAPc2hvd1NraW5MZWZ0QXJtAQEACmZ1bGxTY3JlZW4AAwAIa2V5Lmp1bXAAAAA5AQAGY2xvdWRzAQUAE2NoYXRIZWlnaHRVbmZvY3VzZWQ+4yepAQALdG91Y2hzY3JlZW4AAwAOa2V5LnBsYXllcmxpc3QAAAAPAQALaW52ZXJ0TW91c2UAAQAIc2hvd0NhcGUBAwANYW50aWFsaWFzTW9kZQAAAAEDAAtmb3JjZUhlaWdodAAAAAABAA1mYW5jeUdyYXBoaWNzAAMAB2tleS51c2X///+dCAAKbGFzdFNlcnZlcgBod3NzOi8vZWFnbGVyY3JhZnQtc2VydmVyLS1heXVuYW1pMjAwMC5yZXBsLmNvL3NlcnZlcndzczovL2VhZ2xlcmNyYWZ0LXNlcnZlci0tYXl1bmFtaTIwMDAucmVwbC5jby9zZXJ2ZXIFABB2b2ljZVNwZWFrVm9sdW1lPwAAAAA=
----- End Minecraft Config -----

window.minecraftServer = undefined

**Comment by LunaAmani48** [comment]
Can you try to reset the game on https://totallyscience.co/class?class=Minecraft. Thanks ;)

**Comment by divxtotal2** [comment]
all totallyscience games
[](https://totallysciences.one/)

**Comment by divxtotal2** [comment]
https://totallysciences.one/
